const constants = {
    SELECT_REGION : 'SELECT_REGION',
    SELECT_DATE_RANGE : 'SELECT_DATE_RANGE',
    REQUEST_PRODUCTS : 'REQUEST_PRODUCTS',
    PRODUCTS_RETRIEVED_SUCCESS : 'PRODUCTS_RETRIEVED_SUCCESS',
    PRODUCTS_RETRIEVED_FAILURE : 'PRODUCTS_RETRIEVED_FAILURE',
    GET_TOTAL_NUMBER_OF_PRODUCTS : 'GET_TOTAL_NUMBER_OF_PRODUCTS',
    PRODUCT_REQUEST : 'PRODUCT_REQUEST',
    BASE_URL: 'http://localhost:3000/'
}

export default constants